version: '3'

services:
  web:
    # container_name: node_docker_web
    # image: node:8.13.0
    image: node_web
    build: .
    command: "bash -c 'echo Waiting 20 seconds for DB to init; sleep 20; npm start;'"
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app 
    depends_on:
      - db

  db:
    # container_name: mysql_db
    image: mysql:5.7.24
    command: --init-file /app/init.sql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
      MYSQL_USER: mail_user
      MYSQL_PASSWORD: mail_user
    ports:
      - 6033:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - .:/app
#     networks:
#       - mynet

# networks:
#   mynet: