version: '3'

services:
  web:
    image: oubrahemnissa/node-web:lataset
    command: "bash -c 'echo Waiting 20 seconds for DB to init; sleep 20; npm start;'"
    #restart: always
    #condition: on-failure
    # deploy:
    #   replicas: 2
    #   resources:
    #     limits:
    #       cpus: "0.2"
    #       memory: 500M
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app 
    depends_on:
      - db

  db:
    image: mysql:5.7.24
    command: --init-file /app/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
      MYSQL_USER: mail_user
      MYSQL_PASSWORD: mail_user
    ports:
      - 6033:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - .:/app
